#!/bin/bash
#
# Copies fixture projects into the test bundle directly, so they don't have to
# be added to the Carthage workspace. This avoids confusing Xcode with
# "subprojects" that are actually just originating from a fixture.

destination="${BUILT_PRODUCTS_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}"

for fixture in "ReactiveCocoaLayout" "CartfilePrivateOnly" "SchemeDiscoverySampleForCarthage-0.2" "Swell-0.5.0" "SampleMultipleSubprojects" "SampleGitSubmodule"
do
	rm -Rf "$destination/$fixture"
	unzip -q -d "$destination" "Source/CarthageKitTests/fixtures/$fixture.zip"
done
