#!/bin/bash
#
# Copies fixture projects into the test bundle directly, so they don't have to
# be added to the Carthage workspace. This avoids confusing Xcode with
# "subprojects" that are actually just originating from a fixture.

for fixture in "ReactiveCocoaLayout"
do
	destination="${BUILT_PRODUCTS_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}/$fixture"
	rm -Rfv "$destination"
	cp -Rv "CarthageKitTests/fixtures/$fixture" "$destination"
done
