#!/bin/bash -e

main()
{
    local version=$(git describe --tags)
    /usr/libexec/PlistBuddy -c "Set CFBundleShortVersionString $version" "${BUILT_PRODUCTS_DIR}/carthage.app/Contents/Info.plist"
}

main
