#!/bin/bash -e

main()
{
    local version=$(git describe --tags)
    local DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
    /usr/libexec/PlistBuddy -c "Set CFBundleShortVersionString $version" "$DIR/../Source/CarthageKit/Info.plist"
}

main
