name: Test

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:

jobs:
  test:
    runs-on: macOS-10.14
    strategy:
      matrix:
        xcode: [10.1, 10.3]
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app
    steps:
    - uses: actions/checkout@v1
    - run: make test
